name: onlineShopUIKit
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  rules: ^1.2.0+1
  flutter_inner_drawer: "^0.5.7+2"
  provider: ^4.3.2+2
  flutter_colorpicker: ^0.3.4
  page_transition: "^1.1.7+2"
  eva_icons_flutter: ^2.0.1
  pinput: ^0.2.0
  titled_navigation_bar: ^4.1.0
  flutter_slidable: ^0.5.7
  progress_timeline: ^0.0.5
  stepo: ^1.0.0
  ayn_stepper: ^0.0.3
  timeline_tile: ^1.0.0
  steps_indicator: ^1.1.0
  flushbar: ^1.10.4
  fluttertoast: ^7.1.1
  cached_network_image: ^2.3.3
  circular_check_box: ^1.0.4
  font_awesome_flutter: ^8.10.0
  flutter_timeline: ^0.1.1+13
  timeline_list: ^0.0.5
  animate_icons: ^0.0.4
  credit_card_slider: ^1.0.1
  simple_animations: ^2.2.3
  double_back_to_close_app: ^1.2.0
  carousel_slider: ^2.3.1
  carousel_pro: ^1.0.0
  carousel_indicator: ^1.0.5
  shared_preferences: ^0.5.12+4
  progress_dialog: ^1.2.4
  floating_bottom_navigation_bar: ^1.4.1
  fluentui_system_icons: ^1.1.88
  smooth_page_indicator: ^0.2.0
  quiver: ^2.1.5
  auto_size_text: ^2.1.0
  touchable_opacity: 1.1.2
  floating_action_row: ^0.1.0
  flutter_html:
  tap_builder: ^0.1.3

  vibration: ^1.7.1
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/banner.jpg
    - assets/images/woman.jpg
    - assets/images/man.jpg
    - assets/images/app_icon.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Black.ttf
        - asset: assets/fonts/Rubik-BlackItalic.ttf
        - asset: assets/fonts/Rubik-Bold.ttf
        - asset: assets/fonts/Rubik-BoldItalic.ttf
        - asset: assets/fonts/Rubik-ExtraBold.ttf
        - asset: assets/fonts/Rubik-ExtraBoldItalic.ttf
        - asset: assets/fonts/Rubik-Italic.ttf
        - asset: assets/fonts/Rubik-Light.ttf
        - asset: assets/fonts/Rubik-LightItalic.ttf
        - asset: assets/fonts/Rubik-Medium.ttf
        - asset: assets/fonts/Rubik-MediumItalic.ttf
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-SemiBold.ttf
        - asset: assets/fonts/Rubik-SemiBoldItalic.ttf

  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
